### ISSUE TITLE
conversion.analysisToolLogFileLocation should be an array

### ISSUE THREAD

**Issue by lgolding** [oasis-tcs/sarif-spec#134]
Some analysis tools emit multiple files. A converter might need more than one of them to produce a SARIF log file. So the property `conversion.analysisToolLogFileLocation` of type `fileLocation` should be changed to `analysisToolLogFileLocations` of type `fileLocation[]`.

**Comment by lgolding** [comment]
@kupsch @michaelcfanning  Nobody has cited a tool that needs this, so I'm closing it.

**Comment by kupsch** [comment]
The clang static analyzer outputs a directory of results.  There are one to two files per issue found, plus a small number of files per assessment.

**Comment by kupsch** [comment]
there are also tools that can be configured to output the same results in different formats for the same analysis.

**Comment by lgolding** [comment]
@kupsch @michaelcfanning Alright, I'll reopen this. Your first example is compelling: we have multiple native files both per run and per result.  The second example is less compelling; presumably a converter wouldn't need to consume the same results in multiple formats.

**Comment by lgolding** [comment]
Our existing Clang Analyzer converter consumes a single XML file and produces a single SARIF file containing multiple results. See for example [src/Sarif.FunctionalTests/ConverterTestData/ClangAnalyzer/FileNumberCoverage.xml](https://github.com/Microsoft/sarif-sdk/blob/master/src/Sarif.FunctionalTests/ConverterTestData/ClangAnalyzer/FileNumberCoverage.xml) and [FileNumberCoverage.xml.sarif](src/Sarif.FunctionalTests/ConverterTestData/ClangAnalyzer/FileNumberCoverage.xml.sarif) in the SARIF SDK.

So @kupsch could you clarify: Do later versions of Clang Analyzer use these multiple per-run and per-result files? Or @michaelcfanning, did _our_ converter have these multiple files available but chose to use only one of them? ... and a more ambitious converter might have made a different choice of which files to consume?

**Comment by lgolding** [comment]
@kupsch @michaelcfanning Ping on this. Jim explained that Clang Analyzer emits multiple files on a per-run basis in addition to its per-result files. But our converter consumes only a single file. I'm curious about:
1. @michaelcfanning  Why does our converter consume only one file? Is it leaving some good information on the table by ignoring these other files?
2. @kupsch  What is the nature of the information in these per-run files?

**Comment by kupsch** [comment]
If you have the clang compiler directly run the analyzer on the output, then there is only one file, but you can also run the analyzer using scan-build which analyzes an entire build.

If you use scan-build script to analyze a build, then it creates a uniquely named directory that contains many files.  In this case, it necessary to generate both html and plist files to get all the details.  In that directory there is an index.html (containing links to all report-xxxxxx.html files), one report-xxxxxx.html file per weakness, and one report-zzzzz.plist file per source file.  The plist file contains the name(s) of the html files.  The html files are still necessary, since the file name in the plist file is just a file name with no directory information, whereas the html file contains the full path the file.

**Comment by lgolding** [comment]
@kupsch Thanks, got it! I'll write the words for this now.
