### ISSUE TITLE
correlationGuid property on run object should be on result object

### ISSUE THREAD

**Issue by EasyRhin0** [oasis-tcs/sarif-spec#196]
Property added by Issue #158 and mistakenly placed on the run object.

**Comment by lgolding** [comment]
This is a mistake in the schema. @michaelcfanning  FYI, @EasyRhin0 discovered this yesterday.

**Comment by michaelcfanning** [comment]
We definitely need a correlation guid for results. Didn't we also define one for runs? This is basically a logical id but in the form of a guid, just as the schema says.

So the schema has it on run, the spec has it on result. We should look at our meeting notes to see if we can discover past intent.

**Comment by lgolding** [comment]
@michaelcfanning @EasyRhin0 

According to the spec (which is correct according to the discussions we had):

The `run` object has:
- a GUID-valued `instanceId` property that uniquely identifies the run.
- a hierarchical-string-valued `logicalId` property, for example `"Nightly security scanner run/x86/debug"`.

The `result` object has:
- a GUID-valued `instanceId` property that uniquely identifies the result.
- a GUID-valued `result.correlationGuid` property allows us to associate (correlate) multiple results that are logically identical. There is no corresponding concept for `run`.

The schema in the OASIS repo incorrectly places `correlationGuid` on `run` rather than on `result`.

**Comment by michaelcfanning** [comment]
But you see my point, yes? That correlationGuid is effectively a logical identifier expressed as a GUID. Are you sure we haven't discussed the utility of this on the run object? I have a sense that we have. But my recollection isn't clear and so is suspect.

**Comment by lgolding** [comment]
Sorry, I don't recall discussing the need for a `run.logicalGuid` in addition to its existing properties `instanceGuid` and `logicalId`. To the best of my recollection, the four properties I mentioned above were where we landed.

**Comment by lgolding** [comment]
Could you explain what utility `run.logicalGuid` would add to the existing properties?

**Comment by michaelcfanning** [comment]
the property would be named 'correlationGuid'. it would serve the same function as 'logicalId' except that the semantics of populating the property are clear, it should be a GUID. generally, this slot might be an alternate to the logical id. the logical id is a more readable id that supports hierarchical data.

i thought we proposed this purely to allow for result management systems that consistently utilize guids for storing various things. the instanceGuid and baselineGuid argues, from a certain perspective, for a correlationGuid.

**Comment by michaelcfanning** [comment]
Looking at the schema, though, I clearly see that the description does, in fact, refer to result.correlationGuid.

**Comment by lgolding** [comment]
@michaelcfanning 

That's correct. This is a bug in the schema that we need to fix. I fixed it and pushed the change to the TC repo. The version of the schema in the sarif-sdk repo was correct.

Now, having moved `correlationGuid` from `run` to `result`, which is where it belonged... you raised the separate issue of whether `run` requires a `correlationGuid` in addition to its existing `logicalId` property.  Your proposed semantics is that it serve the same function as `logicalId`, but in GUID form.

I opened #220 to track this question.
