### ISSUE TITLE
Random-access readable format

### ISSUE THREAD

**Issue by katrinaoneil** [oasis-tcs/sarif-spec#199]
Quoting my colleague: "JSON is only marginally better than XML. A file needs to be random-access readable to enable scalability of viewers. If a viewer has to parse human-readable text of an entire scan result before meaningful user interaction can begin, then the file format should be abandoned."

**Comment by michaelcfanning** [comment]
This issue is tracking a substantive issue raised in our public feedback period for CSD.1. BSON is presumed to provide the ability to randomly access SARIF contents. We will update the spec to separate the OM content from the format-specific information, noting that JSON may be used in one expression, while BSON could be used for this scenario. 

Other substantive changes related to improving performance in read/write scnearios covered in #210.

This specific issue is classified as being addressed at editorial discretion with no further discussion required.

**Comment by lgolding** [comment]
We are investigating a random access binary serialization for JSON but will not publish it as part of SARIF v2.0.

**Comment by lgolding** [comment]
@michaelcfanning Please add any further comments you have about your discussions with Micro Focus on this issue.
