### ISSUE TITLE
3.11.18: require everything to be UTF-8

### ISSUE THREAD

**Issue by katrinaoneil** [oasis-tcs/sarif-spec#200]
Quoting my colleague: "Don't allow ambiguity that results in "unknown" encoding. Force conversion of non-UTF8 files to UTF8 prior to inclusion in results. Enable viewers to be UTF8 only, rather than requiring viewers to have to try to detect file encodings (the analysis tool will have already done that...)"

**Comment by katrinaoneil** [comment]
Same goes for 3.11.19: UTF8 should be used, not UTF16.

**Comment by michaelcfanning** [comment]
Per TC#20, we believe this topic is covered correctly by the spec. All textual snippets embedded in SARIF are required to be UTF-8. We cannot require conversion of files under analysis, embedded in SARIF, etc. to be converted to UTF-8. This isn't possible in the conversion case. In other cases, an analysis platform might not have the capability to detect/emit the coding (without taking a platform change).

And so, the spec should strongly recommend that producers express the file encoding where possible. 

We leave it to editorial discretion to ensure this is properly communicated in the spec.

**Comment by lgolding** [comment]
I agree that the spec says as much as it can about encoding:
- The SARIF log file must be encoded in UTF-8 (§3.1).
- As a result, embedded file content (`fileContent.text`, §3.2.2) must be UTF-8 (transcoded from the original file encoding if necessary).
- `file.encoding` (§3.19.9) is optional, and if absent, the original file encoding is taken to be unknown.

I believe it's that last point that @katrinaoneil's colleague objects to, but it's unavoidable in some cases. For example, Semmle takes a _snapshot_ of a code base, saves the snapshot in UTF-8, and then analyzes the snapshot. Once the snapshot is taken, Semmle does not remember the original file encoding.

That might seem to imply that the encoding in this case is UTF-8. The problem is that if the SARIF file includes `fix` objects, those fixes might refer to the wrong portion of the original file if that file is in any other encoding. In this scenario, the SARIF log file needs to record the fact that it just doesn't know the original file encoding.
