### ISSUE TITLE
Make region kind more explicit

### ISSUE THREAD

**Issue by michaelcfanning** [oasis-tcs/sarif-spec#201]
We should consider requiring an explicit indicator of the kind of a region. This means that one of startLine, charOffset or byteOffset must be present. Everything else can be used as a default. This would restrict the # of properties that need to be nullable types.

Currently, a region can be emitted with absolutely no offset/size other details. This is implicitly a binary region that consists of an insertion point at the beginning of the file.

In SDKs such as C#, charOffset and byteOffset should be nullable, so that their non-presence is a clear indicator of text vs. binary item. startLine can be non-nullable and default to zero, as this is a 1-indexed property. The logical for determining whether a region is binary or textual looks like so:

if (startLine > 1 || charOffset != null) region is textual

thinking this through again from the C# standpoint, only charOffset would need to be nullable type for everything to work. charLength also must be nullable, otherwise you can't use it to help specify a zero-length insertion point. 

region { startLine = 1 } // this region is all of line 1
region { startLine = 1, startColumn = 1} // this region is all of line one

region { startLine = 1, charLength = 0 } // this region is an insertion point at the start of line 1
region { startLine = 1, startColumn = 1, charLength = 0 } // this region is an insertion point at the start of line 1

**Comment by michaelcfanning** [comment]
Change approved per TC #20. start and end locations must be explicitly specified (in their entirety) in either the charOffset/charLength pair or the startLine/EndLine combinations. i.e., if startLine > 1, all other data s/be implied to comprehensively describe the region (even if that expression derives from default values). similarly, in the case where charOffset > 0 or charLength > 0, then the remaining charXXX property is assumed to be correct and to finish describing the region.

In cases where both property domains are expressed, the implied regions s/be equivalent.

After making this change, we should update all the examples. It is useful in the examples for the doc to describe the comprehensive textual content of each region under discussion.

**Comment by michaelcfanning** [comment]
Technical issue with no further discussion required.

**Comment by lgolding** [comment]
@michaelcfanning This is now moot since we implemented #204. **I am closing this issue.**

As the spec now stands:

- If `startLine` is present, we know that we can calculate the character extent of the region by examining only the line/column properties (using defaults for any missing ones).
- If `charOffset` is present, we know that we can calculate the character extent of the region by examining only the character offset/length properties (using defaults for any missing ones).
- If both `startLine` and `charOffset` are present, the region specified by the line/column properties and the region specified by the character offset/length properties must be identical.
- If `byteOffset` is present, we can calculate the byte extent of the region by examining only `byteOffset` and `byteLength` (using the default for `byteLength` if it's missing).
- If both a character extent and a byte extent are inferrable from the region properties, they must specify the identical portion of the file (although in general you can't be sure that they do unless you also know the file's encoding).
- The SDK can represent "missing" `charOffset` and `byteOffset` properties by defaulting them to -1.
