### ISSUE TITLE
Remove uniqueItems constraint from result.locations

### ISSUE THREAD

**Issue by kupsch** [oasis-tcs/sarif-spec#223]
In converting SWAMP results to SARIF, there was a validation failure that a tool produced two identical locations for a result.  The problem is that the tool does not include column information, and generated a weakness that the "left and right expressions of the '-=' operator were identical" for a source line

x -= x;

The tool output the same file, line and message for the two expressions (which seems reasonable), and without the column information, the location elements in SARIF are identical.

Should the restriction be removed from SARIF (at least if column data is not present), or should this be translated to SARIF to only have one location if the lines are identical.

**Comment by michaelcfanning** [comment]
x -= x; x -= x; x -= x;

imagine a case such as the line above. these are three unique instances of the same problem, which could all be on the same line.

as long as tools aren't required to differentiate these by column location, then i agree the uniqueness requirements is burdensome. is there a problem with dropping it entirely? I don't think, in general, there is an issue with tools inadvertently duplicating information.

OTOH: we have an internal request here (by an accessibility tools team) to provide a 'count' property for a result. if we proceeded this way, the producer would emit a single result and increment the count property (and we would retain the requirement that results be unique). this solution would simplify the life of consumers.

the accessibility scenario: a set of results are generated while executing a series of automated web tests. accessibility issues are captured during this process, which resolve to an identical code location. rather than emitting all these non-unique issues, the tool producer would like to collapse them into a unique issue, by location, with a corresponding 'count' (to help rank/prioritize them). this seems like a reasonable request and would also resolve this issue.

**Comment by kupsch** [comment]
The Sarif.Multitool Validator flagged this as an issue.  The JSON schema validators did not.

**Comment by lgolding** [comment]
@kupsch @michaelcfanning 

Hang on, this is not the same bug. Although the SARIF schema (correctly) allows non-unique elements in `run.results`, requires unique elements in `result.locations`. This is a mistake for the same reason requiring unique results is a mistake -- namely, that some tools might emit duplicates if they only report the line number. But those two problems are exhibited by different tools. #75 is exhibited by tools that report the two observations as two distinct but identical results; #223 (this issue) is exhibited by tools that report the observations as a single result with two distinct but identical locations.

Jim, one thing you need to know is that the SARIF Multitool validator _first_ performs a schema validation, and _then_ applies a set of custom rules for requirements that JSON Schema cannot express. So it is not surprising that the validator would report this error.

The question is, why do "JSON Schema validators" not report the error? They should.

In any case, I will fix this in the schema for the next TC meeting.

**Comment by lgolding** [comment]
There is no longer a mystery: Per email from Jim's student Bugh, the JSON schema validator _did_ report the error. The statement [above](https://github.com/oasis-tcs/sarif-spec/issues/223#issuecomment-423539216) that it did not is in error. So I will just remove the `uniqueItems` constraint from `result.locations`.
