### ISSUE TITLE
Consider making deconstructed external fragments files that can be validated against our schema

### ISSUE THREAD

**Issue by michaelcfanning** [oasis-tcs/sarif-spec#224]

**Comment by lgolding** [comment]
@michaelcfanning I didn't see this issue and filed #235, "Wrap externalized files with contextual information", that provides details of a proposed design.

Despite the title of this issue, the external fragment files cannot be validated against the SARIF schema; they will need a separate (very small) schema to describe the few properties they contain. I will propose the schema as part of the change draft.

Despite the fact that you filed this issue first, I'm going to resolve this one as "duplicate", because #235 has all the details.
