### ISSUE TITLE
sarif-schema.json has invalid requirement on stackFrame object

### ISSUE THREAD

**Issue by fishoak** [oasis-tcs/sarif-spec#225]
In 'sarif-schema.json', the stackFrame object has:

      "required": [ "fullyQualifiedLogicalName" ]

but that field isn't specified for that object. This is in the CSD version as well as the one under Schemata.

It's an easy fix, on the assumption that it's vestigial and just needs to be deleted.

**Comment by michaelcfanning** [comment]
thanks, paul. will look at this immediately.

**Comment by fishoak** [comment]
I have a fix in pull request #227.

**Comment by lgolding** [comment]
This is fixed in the copy of the schema in this repo, as well as the copy in the sarif-sdk repo. The change is about to be pushed to schemastore.org, and is included in version 2.0.0-csd.2.0.3 of the Sarif.Sdk NuGet package, which we are about to publish.

@michaelcfanning Once you have pushed to schemastore and NuGet, please mark this issue `resolved-fixed` and close it.

**Comment by lgolding** [comment]
[Sarif.Sdk 2.0.0-csd.2.0.3](https://www.nuget.org/packages/Sarif.Sdk/2.0.0-csd.1.0.3) is published to NuGet, and the version at http://json.schemastore.org/sarif-2.0.0 has the fix.
