### ISSUE TITLE
We do not have an automationGuid to match automationLogicalId

### ISSUE THREAD

**Issue by michaelcfanning** [oasis-tcs/sarif-spec#229]

**Comment by lgolding** [comment]
@michaelcfanning We have the property `run.correlationGuid` that is intended to hold (for example) the VSTS GUID that identifies the "build definition". Are you proposing to rename it to "automationGuid"? (If so that would be great -- I never liked "correlationGuid" for this.) Or are you saying we're still missing a concept?

**Comment by lgolding** [comment]
@michaelfanning I am going to close this as duplicate of #217, "Consider adding a discrete id object," since that's where we landed in terms of addressing this.
