### ISSUE TITLE
Consider not requiring rule.id

### ISSUE THREAD

**Issue by lgolding** [oasis-tcs/sarif-spec#233]
Elsewhere in the spec, when certain identifying properties of an object in a dictionary match the dictionary key, they can be omitted. For example, in the logical locations dictionary, this entry:
```
"logicalLocations": {
  "System": {
    "name": "System",
    "fullyQualifiedName": "System",
    "kind": "namespace"
  }
}
```
... can be written without the `name` and `fullyQualifiedName` properties, since they match the dictionary key:
```
"logicalLocations": {
  "System": {
    "kind": "namespace"
  }
}
```

But in the `rules` dictionary, `rule.id` is required even in the overwhelmingly most common case where it matches the dictionary key. This is legal:
```
"rules": {
  "TEST0001": {
    "id": "TEST0001",
    ...
  }
```
... but this is not:
```
"rules": {
  "TEST0001": {
    ...
  }
```
I think it should be allowed.

**Comment by lgolding** [comment]
@michaelcfanning FYI

**Comment by michaelcfanning** [comment]
Our design should certainly be consistent. As a design principle, we generally want to avoid a requirement to recapitulate information already expressed elsewhere.

The subtle outcome of taking your suggestion is that the value that's persisted to the dictionary is not complete (i.e., you can only inspect/understand it properly if you consider/have access to the key that is used to store it in the dictionary).

We have a problem in our SDK visitor that relates: overrides of things like VisitFileData aren't provided the key associated with the visited item.

And so, there's the balance: compactness/readability vs. ease of consuming the populated objects. I think there's merit to both sides. I tend to think we should favor not repeating the information, personally. Since this is a small change, perhaps you could prepare it and we could discuss each general option to the TC to get feedback there.
