### ISSUE TITLE
logicalLocation.kind: remove "package"

### ISSUE THREAD

**Issue by lgolding** [oasis-tcs/sarif-spec#279]
Per @kupsch:

> Add "class" to handle C++'s "class".  Without [it], "module" seems like the closest fit.  There is current work on a module system for C++, I do know any more.

**Comment by michaelcfanning** [comment]
'type' was intended to be the umbrella term that covers C++ classes referenced in a logical location. there may be a bit of imprecision in handling things this way. but doing so prevents the proliferation of enum kinds that has caused problems in other areas of the spec. presumably, no tool would find it useful to distinguish between a 'type' and a 'class' in its own output. (i.e., there is really only a case for two terms if there is a good reason a single producer would want to use both). we also ejected 'interface' from the set of enum values when we defined the current set (arguably a more painful cut since the distinction between a concrete type and an abstraction it implements is clearly useful within a single tool run).

To make the case for 'class', we need to understand the rationale. This enum isn't intended to precisely describe the nature/semantics of the thing it decorates. It provides some rough bucketing useful for building tree hierarchies and assigning icons. It was mostly required in the design to help resolve name collisions that might otherwise occur. Note another 'collapsing' we accepted, defining 'member' only instead of the great range of possibilities here (events, fields, properties).

Thinking about the above, and looking at current definitions, I see two changes that i would propose: first, consider dropping 'function' entirely in favor of 'member'. Second, I'm not sure why 'package' is on the list, since this is a root container and not a logical construct.

**Comment by lgolding** [comment]
I agree with @michaelcfanning that `type` is the right value to use for a class. @kupsch, I propose to close this, `resolved-by-design`.

**Comment by michaelcfanning** [comment]
What are your thoughts on my other suggestions? i.e., remove 'package' as this is a root physical container and not a logical construct.

Along the lines of the 'type' generalization, a 'function' is simply a 'member' of a type and so we can lose that one as well.

**Comment by lgolding** [comment]
I'd like to keep `function`. The `kind` values are intended to be useful to the end user, not to carry precise semantics, so I don't think we need to make them "minimal" or "orthogonal" or any of those nice qualities they'd need to have if they were part of an API.

About "package": yes, it refers to a collection of files and resources, so not a logical location. Do you remember why we included it? Was there some logical construct for which we could find a better name than "package"? Or just drop it? Ok with me either way.

**Comment by michaelcfanning** [comment]
As per offline discussion, I believe that we have agreed to removing both 'package' and 'function'. Removing package is non-controversial, as a package is a 'physical' root container itself. We remove 'function' as its presence creates confusion and implies the absence of certain other things (like 'variable') when applied in the most obvious context (a C program).

We should update the spec to make it clear that this enum is intended to provide a scoping mechanism that helps resolve naming collisions should they exist. The canonical example is where a C# namespace in one assembly exactly matches the name of a type defined in another assembly.

For the most part, compilers prevent name collisions in between members and other things (this is possible because the collision space is typically restricted to a single binary).

One corner case may be worth calling out: a nested type is both a member and a type. I suggest that 'type' is preferable for this case.

**Comment by lgolding** [comment]
I renamed the issue to match our conclusion.
