### ISSUE TITLE
baselineState s/be present on all results or none

### ISSUE THREAD

**Issue by michaelcfanning** [oasis-tcs/sarif-spec#284]
We should clarify that baselineState s/be explicit for all results or omitted for all. This will make processing the files much more efficient for results mgmt. systems that, for example, restrict the view to 'new' results only. If baselineState has an implied default value, the consumer would be required to comprehensively examine all results in order to see whether a result suddenly popped up with an explicit baselineState value.

I checked the spec and don't think we discuss this. But I might have missed it somewhere.

**Comment by michaelcfanning** [comment]
Good candidate for a validation rule, by the way.

**Comment by lgolding** [comment]
This makes sense because an analysis tool would never populate `baselineState`. On the other hand, if a SARIF file comes from a query to a result management system, the result management system should know the answer for _all_ results, so if it populates `baselineState` at all, it should be able populate it for all results.

I propose to make this a **SHOULD** rather than a **SHALL** requirement (the issue title "s/be present" doesn't make it clear which you intended), consistent with our principle expressed in #186: "Ensure spec conforms to philosophy around not specifying result mgmt. behavior". Therefore a SARIF validation rule for this requirement would be warning-level rather than error-level.

This suffices for the purposes of the "result explorer" tool you described to me, whose web-based UI wants to know whether to display a "baseline state" column based on examining the first result in the log file (rather than having to look at all the results to see if _any_ of them have `baselineState`). It suffices because:

1. Even if it's just a warning, a SARIF validator would identify the problem with the generated SARIF file and allow the SARIF producer's author to fix it.
2. Even if it's an error, a SARIF producer could still violate the rule, so a web UI that makes a decision based on looking at only the first result could still get it wrong.

**Comment by michaelcfanning** [comment]
The SHOULD vs. SHALL is an interesting discussion. I believe it should be a SHALL in this case. The reason is that the use of baselineStates implies a comprehensive diff of one logical set to another. If you mix in data from two previous diffs, or inject results that haven't themselves been diffed, you've simply provided a broken view. Imagine if you were comparing two files in your favorite diffing tool and, in addition, to showing you lines that moved, were the same, or deleted, it marked four lines in one file as not classified. You would rightly view this as a bug in the differ. Similarly, if you begin to exercise the SARIF diffing machinery, you must be comprehensive and follow the rules.

In general, you're right: a consumer most usefully operates with an understanding of what level of level of validation is or is not taking place. I can confirm that this is extremely important in building useful SARIF-driven features: attempting to somehow account for the great range of diversity in the format and tools production is a lost cause if you want to produce a consistent experience.

But I don't think diffing falls into this case: if you provide broken diff to any UI, the UI is in an untenable position unless it disregards all the information you've provided. That is, this standard doesn't represent a philosophy or one approach of many for populating the property. Instead, the SHALL requirement reflects the single, precise semantics of the scenario the property supports (the comprehensive diffing of two logically equivalent result sets).

**Comment by lgolding** [comment]
You've convinced me. I updated the change draft as follows:

> If `baselineState` is present on any `result` object in the containing `run`, it **SHALL** be present on every such `result` object.
>
> NOTE: The presence of `baselineState` on any `result` implies that the SARIF producer performed a comprehensive comparison between the results in the current run and those in some previous run. A SARIF consumer is entitled to expect that the differencing operation produced a `baselineState` value for every result.
>
> This is conceptually similar to tool that compares two text files, and for every line, concludes that it exists in the left-hand file, the right-hand file, or both. The tool must provide this information for every line in both files; it cannot leave some lines “undetermined.”

**Comment by michaelcfanning** [comment]
looks good. fix your typo in 'similar to tool that'. :)

**Comment by lgolding** [comment]
Fixed.
