### ISSUE TITLE
Introduce result.taxonomies

### ISSUE THREAD

**Issue by lgolding** [oasis-tcs/sarif-spec#3]
As discussed in the TC meeting of 2017/09/20: Introduce a new property `result.taxonomies`, as follows:

### taxonomies property
The `result` object **MAY** contain a property `taxonomies` whose value is an object. Each property name in the object **SHALL** denote a particular taxonomy for classifying the result. The corresponding property value **SHALL** be an array of one or more `classification` objects which specify the classification of this result with respect to the specified taxonomy.

EXAMPLE:
```
results: [
  {
    ...
    taxonomies: {
      "CWE": [                                        # an array of classification objects
        {                                             # a classification object
          "id": "CWE-396",
          "description": "Divide by zero"
        }
      ]
    }
  }
]
```
SARIF defines the following property names for the object contained in the `taxonomies` property, with the following meanings.
- `CWE`: The Common Weakness Enumeration taxonomy [_link, cite as normative_]

Any property name not appearing in this list **MUST** begin with the prefix `x-`. This prefix means that the property name is not defined in the SARIF standard, and that its meaning, and the meaning of any associated `classification` objects, must be agreed to by convention between the producers and consumers of any SARIF log files in which it appears.

### General
A `classification` object specifies the classification of a result with respect to a particular taxonomy. Some results might have multiple classifications with respect to a single taxonomy. See Section <result.taxonomies> for an example.
### id property
A `classification` object **SHALL** contain a property named `id` whose value is a string that uniquely identifies this classification within the taxonomy.
### description property
A `classification` object **MAY** have a property named `description` whose value is a string that describes this classification.

**Comment by michaelcfanning** [comment]
I'm not sure I think this is a good idea. Some points:

- This approach encourages log file producers to emit information, such as CWE description, which is not strictly owned by them and which may be fluid. Generally, we want to minimize packaging supporting metadata if we can (for example, this is why others have suggested referencing rules metadata by URI rather than embedding)
- I clearly understand the need for CWE as a common taxonomy but am not sure that others exist which are likely to be utilized. We shouldn't design significant structure if CWE is the only likely candidate to populate
- In general, this simply looks like a tag to me. I wonder whether we shouldn't just use the tagging mechanism for CWE information. We could allow tags to be 'namespace' or hierarchized by defining a convention such as using a forward slash as a separate. So, an item could be tagged as "CWE/123-123" and also "CWE/456-456". 
- Finally, I'll say that I personally have not seen a case where tagging results provided real value. Tagging schemes across tools are quite divergent. Most tagging schemes aren't themselves self-consistent, even when looking at a single tool or results mgmt. viewer. All this is to say that it's very easy to propose to define substantive categorization schemes but in the main, they don't tend to get far. And so I prefer the very simple, general approach we have in SARIF today.

**Comment by lgolding** [comment]
@michaelcfanning Closing this "wont-fix". We implemented this with hierarchical tags.

**Comment by michaelcfanning** [comment]
This issue came up against in internal Microsoft testing of the SARIF format. Reactivating.

**Comment by michaelcfanning** [comment]
@lgolding, closing again. hierarchical tags satisfy the parties that prompted reactivation. at this point, we have no known active requests for this data. good candidate to note in the editor's report.
