### ISSUE TITLE
Define result taxonomies

### ISSUE THREAD

**Issue by michaelcfanning** [oasis-tcs/sarif-spec#314]

**Comment by michaelcfanning** [comment]
1. Remove `properties.tags`
2. Add `result.tags`.
3. Add `rules.tags`.
4. Add `rule.optionalTags`.

Driving scenario: taxonomy: I detect CWE/851

tags are hierarchical

**Comment by michaelcfanning** [comment]
The TC thinks this proposal makes sense as it stands. But it suggests the possibility of expanding this idea so that the CWE tag references can provide linkage to comprehensive metadata on the related CWE/other classification.

It would be helpful to review this broader issue. Please review #3 and take look.

**Comment by michaelcfanning** [comment]
Let's commit to having this closed by TC#32.

**Comment by michaelcfanning** [comment]
We propose to create a set of reporting descriptors at the sarif log level 'taxonomies'. The tags associated with a result or a rule would be an array of objects that locate data in the taxonomies array. Each item would consist of an id and an index into the taxonomies data, if it exists. The array index would be optional, so that users could simply mark items with the readable id.

**Comment by michaelcfanning** [comment]
TC accepts this change.

**Comment by michaelcfanning** [comment]
Change here is that taxonomies object moves to 'run'.

**Comment by kupsch** [comment]
The design for result and reportingDescriptor is good, but I think how the taxonomy data is stored  needs changes that are going to be discuss soon with Michael and Larry.  I also think that the toolComponent should declare the taxonomies that it uses.

**Comment by michaelcfanning** [comment]
Per offline discussion, result.ruleExtensionIndex s/be renamed to ruleCompont, the type of which is a componentIdentity.

**Comment by lgolding** [comment]
#### E-BALLOT <span>#</span>3 PROPOSAL

Represent standard taxonomies by reusing the existing `toolComponent` and `reportingDescriptor` types. A standard taxonomy is a `toolComponent` that contains `taxonomyDescriptors` (an array of `reportingDescriptor`s), but does not contain `ruleDescriptors` or `notificationDescriptors`.

Allow tool components to define their own custom taxonomies by including `taxonomyDescriptors` along with `ruleDescriptors` and `notificationDescriptors`.

#### SCHEMA CHANGES

- In the `toolComponent` object:

    - Add a property `taxonomyDescriptors` of type `reportingDescriptor[]`: allows definition of both standard and per-tool taxonomies.
    - Add a property `supportedTaxonomies` of type `toolComponentReference[]`: allows a tool to declare the taxonomies it supports.

- In the `reportingDescriptor` object:

   - Add a property `taxonomyReferences` of type `reportingDescriptorReference[]`: the set of taxonomic categories that apply to all results implicated by this rule.
   - Add a property `optionalTaxonomyReferences` of type `reportingDescriptorReference[]`: a set of taxonomic categories that can _optionally_ apply to results implicated by this rule.

- In the `result` object:

    - Add a property `taxonomyReferences` of type `reportingDescriptorReference[]`: the set of optional taxonomic categories into which this result falls (the "required" taxonomy references apply implicitly).

NOTE: Unlike in the previous proposal, it is _not_ necessary to explicitly declare "taxonomies" as externalizable, since they are `toolComponents`, which are already externalizable through the `driver` and `extensions` properties of the `externalPropertyFile` and `externalPropertyFileReferences` objects.

**Comment by lgolding** [comment]
Approved in e-ballot-3 (as modified by #338).
