### ISSUE TITLE
Remove current localization mechanism

### ISSUE THREAD

**Issue by michaelcfanning** [oasis-tcs/sarif-spec#325]

**Comment by michaelcfanning** [comment]
Verify with GrammaTech that they don't intend to use the feature, otherwise remove.

**Comment by michaelcfanning** [comment]
As a consequence of this, we no longer require tool.name to be a message (as it can no longer be localized). Instead it can revert to being a string.

@lgolding

**Comment by lgolding** [comment]
Paul confirmed that Grammatech isn't using this feature. In an email, I gave four reasons for removing it:

1.	It’s not exercised. I’m not aware of any SARIF-producing tool that offers multiple language output. (If there were one, I’ll bet it’s author would have complained about <span>#</span>4 below!)
2.	Michael has always objected that the current design imposes constraints on how tools store arrange their resource files on the file system or on the web. I’ve argued back that this is necessary to allow tools to locate resources for other languages, but that doesn’t make it a good design.
3.	It’s not useful, as I argued in the email “tool.language considered unnecessary.”
4.	It’s badly designed. It’s always bothered me – and I should have raised this earlier; it’s just something I swept under my mental rug – that the contents of run.resources are a mix a localizable strings and on-localizable metadata. That is, the rule object (as of #311, the reportingDescriptor object) includes messageStrings and richMessageStrings (localizable) and configuration (level, rank, and parameters: non-localizable). So if you duplicate the resources into multiple languages, you have to keep the rule metadata in sync across all of them.

**UPDATE** We now have a customer at MS who wants to localize their SARIF files, but @michaelcfanning, @kupsch, and I agree that the current design will not serve, mostly due to reason <span>#</span>4. This proposal removes the current, inadequate design. We are working on a replacement, but it's not ready, so it is not on the e-ballot.

**Comment by michaelcfanning** [comment]
**EBALLOT PROPOSAL**: remove existing localization mechanism. See above for rationale.

**API IMPACT**
Remove 'tool.language'
'reportingDescriptor.name' is typed as a string value again, not a message
'exception.message' is typed as a string value again, not a message

**NOTES**
The TC is developing a new proposal for localization that may replace the current mechanism that we propose to remove (due to its obvious flaws).

**Comment by lgolding** [comment]
Approved in e-ballot-3.
