### ISSUE TITLE
Consider formalizing sub-rules in rules metadata

### ISSUE THREAD

**Issue by michaelcfanning** [oasis-tcs/sarif-spec#329]

**Comment by lgolding** [comment]
@michaelcfanning This looks like a duplicate of #146, "Make result.ruleId a hierarchicalString". That's already done and in the spec:

> Depending on the circumstances, a `result` object either **SHALL** or **SHALL NOT** contain a property named `ruleId` whose value is a hierarchical string (§3.5.4) consisting of one or more components, the first of which is the stable, opaque identifier of the rule that was evaluated to produce the result.

If there is more to this issue than that, please drop in a descriptive comment (but I think you'd agree it's too late to take this in v2). Otherwise, please label this `resolved-duplicate` and close.

**Comment by michaelcfanning** [comment]
It's not a duplicate. The suggestion here was to formalize sub-rules beyond the hierarchical string (e.g., by providing some sort of `parentRule` property. In any case, we are out of design time and can't reasonably tackle this. We do have the new taxonomies work, which can be used by tools to design internal organizational schemes, so that's available to explore rule grouping approaches.

Closing after marking as 'future'.
