### ISSUE TITLE
Rename all 'instanceGuid' properties to 'guid'

### ISSUE THREAD

**Issue by michaelcfanning** [oasis-tcs/sarif-spec#341]

**Comment by lgolding** [comment]
The full set of renames pursuant to this issue is:

In the `run` object:

- Rename the `baselineInstanceGuid` property to `baselineGuid`.

In the `externalPropertyFile` object (which is renamed to `externalPropertyFileReference` in [#335](https://github.com/oasis-tcs/sarif-spec/issues/335)):

- Rename the `instanceGuid` property to `guid`.

In the `runAutomationDetails` object:

- Rename the `baselineInstanceGuid` property to `baselineGuid`

In the `result` object:

- Rename the `instanceGuid` property to `guid`.

In the `resultProvenance` object:

- Rename the `firstDetectionRunInstanceGuid` property to `firstDetectionRunGuid`.
- Rename the `lastDetectionRunInstanceGuid` property to `lastDetectionRunGuid`.

In the `externalProperties` object:

- Rename the `instanceGuid` property to `guid`.
- Rename the `runInstanceGuid` property to `runGuid`.

**Comment by lgolding** [comment]
Approved in e-ballot <span>#<span>2.
