### ISSUE TITLE
3.20.14 toolExecutionSuccessful default too ambiguous

### ISSUE THREAD

**Issue by michaelcfanning** [oasis-tcs/sarif-spec#389]
Consider the following. Since the exit code of non-zero is ambiguous in terms of indicating failure or success, why do we move on to make a conclusive statement about how the default value changes for a non-zero return?

This property becomes clearer if we convert it to 'toolExecutionFailed' and provide a default of 'false'. Now the spec just says: if tool execution failed, set this to true.

This feedback came up in context of me looking at the web request 'no response received' work item accepted by the TC today.

NOTE: This property is needed because not all programs exit with an exit code of 0 on success and non-0 on failure.
If this property is absent, it SHALL default to false if the exitCode property (§3.20.9) is present and has a non-zero value; otherwise it SHALL default to true.

**Comment by michaelcfanning** [comment]
@lgolding

**Comment by kupsch** [comment]
Changing to toolExecutionFailed is clearer and simpler for clients (they don't need to inspect exitStatus (or any of the other failure indicators).  It does requires producers to set toolExecutionFailed to true when their tool doesn't use a non-0 exit status to indicate success.
 
Currently, toolExecutionSuccessful only needs to be set in the case of a tool using a non-0 exit status to indicate a non-failure case.  Most tools that I have seen do not use a non-0 exit status to differentiate variants of a successful execution, but there are some.  If the property were changed to toolExecutionFailed, then it would need to be set to true for all non-0 exit statuses that are truly a failure.

If this change is made, I would also suggest the description state that toolExecutionFailed be SHALL set to true if the process failed for any reason: exitCode that doesn't indicate success, death by signal, or the process failed to start (processStartFailureMessage is set).

It should also be set if the process only indicated failure in a log file even if it did appear successful (started successfully, had an exit status of 0, and did not exit via signal).  This supports a case that is currently not representable in SARIF.

This seems like a reasonable change to make, as simplifies client code, and isn't a big change for producers.

**Comment by michaelcfanning** [comment]
@lgolding, I am withdrawing this feedback. As Jim notes, one implication is that in any failure case of a standard tool (that returns a non-zero result code for failure) this property must also be set. This creates too much of an opportunity for error, it's preferable if our design works easily for the 'happy path' scenario.

**Comment by kupsch** [comment]
On the other hand it does make it much clearer and simpler for consumers as to determine execution failure, they no longer need to check both toolExecutionSuccessful and exitCode; just toolExecutionFailed.

The document implies but does not state that producers still need to set toolExecutionSuccessful (or consumers need to imply this) if the tool exited via a signal (exitSignalNumber or exitSignalName are set) or if the process failed to start (processStartFailureMessage is set). If this change is made then producers would set toolExecutionFailed, and consumers would not need to consider all the ways a process can fail.  The only difference is that currently producers do not need to set toolExecutionSuccessful for a normal non-0 exitCode that truly indicates failure.

Since it simplifies consumers (a big win) and only requires producers to now set a property to indicate a non-0 exit status indicating failure (not very burdensome), I am supportive of @michaelcfanning's proposal, and still making this change.

If the change is not made, please update the documentation to say that toolExectutionSuccessful SHALL be set appropriately if the process fails to start exits via a signal with the value false, or update the description for the default value of toolExecutionSuccessful to be false if the process failed to start, or exited via a signal, which are more tests for the consumer to get right.

**Comment by lgolding** [comment]
@kupsch @michaelcfanning 

We decided to make `toolExecutionSuccessful` required to solve this problem.

**Comment by lgolding** [comment]
@michaelcfanning @kupsch 

Changed title to match what we'll actually do.

**Comment by lgolding** [comment]
@michaelcfanning To answer your original question, "Why do we go on to make a conclusive statement about how the default value changes for a non-zero return?": It is to optimize the happy path. _Most_ programs return 0 on success. So if a tool exits non-zero, you can save space by assuming the tool failed _unless the log file explicitly says otherwise_. Likewise, if a tool exits zero, you can save space by assuming the tool succeeded unless the log file explicitly says otherwise.

Now, this might indeed be too confusing, but that was the rationale.

**Comment by lgolding** [comment]
As @michaelcfanning points out: by making `toolExecutionSuccessful` required, we eliminate all ambiguity. If it's true you succeeded, if it's false you failed, for whatever reason, period.

**Comment by lgolding** [comment]
Categorized as `bug` because the original spec was just too confusing.

**Comment by lgolding** [comment]
I confirm that this change is correctly in the schema.
