### ISSUE TITLE
Consider providing an ability to associate a quality domain with a tool

### ISSUE THREAD

**Issue by michaelcfanning** [oasis-tcs/sarif-spec#413]
At Microsoft, our results management systems aggregate results from multiple quality domains. There is no first-class SARIF construct to express this at the tool level. Arguably, tools can associate individual rule relationships with a taxonomy that documents quality domains. There's no short-hand mechanism for indicating, for example, that all results from a tool are within the 'security' domain. Also, of course, this approach assumes the authoring of a relevant 'quality domains' taxonomy.

**Comment by lgolding** [comment]
Closing for now since it's `future`. @michaelcfanning FYI.

**Comment by katrinaoneil** [comment]
https://cqe.mitre.org/data/index.html :)

**Comment by tk** [comment]
I stumbled upon this because SonarCloud currently allows importing findings in SARIF, but assigns every imported issue to the SECURITY software quality domain. [Reference](https://docs.sonarsource.com/sonarqube-cloud/analyzing-source-code/importing-external-issues/importing-issues-from-sarif-reports#import-process)

Is this still being considered for a future version of the specification, allowing tools to associate findings with a specific quality domain?
