### ISSUE TITLE
Consider: Adding support for metrics

### ISSUE THREAD

**Issue by DerSaidin** [oasis-tcs/sarif-spec#44]
A metric would consist of three things:
- metric type (should include a unit, such as seconds)
- location object  (may be logical or physical location)
- metric value (may be integer or floating point)

**Comment by sdrees** [comment]
I presume location is describing object in terms of line number/range or language specific hierarchical "container", right? ... as a GeoJSON "guy" I think more coarsely 😀

**Comment by DerSaidin** [comment]
"logical location" means language specific hierarchial object, such as function/class/namespace/etc.
"physical location" means file + line number/range

Metrics are mainly useful for logical locations, I think the only "physical location" type one we've wanted to have is on a whole source file.

**Comment by sdrees** [comment]
If we take dynamic analysis / fuzzing findings into account, I think the physical location will also profit from allowing byte offsets and ranges. But I may well be wrong, as I am no vendor in that arena.

**Comment by michaelcfanning** [comment]
@sdrees, you'll be happy to know a physical location can use offset + length to specify regions. 

@DerSaidin, your suggestion makes me think again about the notion of inverting the relationship between locations and results. SARIF is results-oriented (ha!) in that it's effectively designed to render flat lists of tool results. If SARIF was designed to render a set of code locations, each of which could be annotated in a general way, your suggestion could be easily incorporated (locations could be annotated with metrics as easily as with a static analysis result).

As per comments on a separate thread, this design would also facilitate rendering graph relationships. It would be a very disruptive design change, though, we'd want to code up proof points to validate.

**Comment by DerSaidin** [comment]
I would note that (as I understand it) the proposal to make SARIF location oriented is orthogonal to supporting metrics.

- Metrics could be added, not as part of results, but as a separate metrics section. Each metric would refer to a location, and provide its value. This would complement the current results structure, for metric results as opposed to location&message report results. This does not require making SARIF location oriented.

- Making SARIF location oriented could also be done without additionally allowing the locations to be annotated with metrics.

**Comment by fishoak** [comment]
_Below is an informal proposal for metrics for SARIF. I wrote this at the face-to-face meeting on 1/30, and some elements were discussed later that evening._ 

1.1 metric object
_This is modeled after the rule object._
1.1.1 General
A metric object contains information that describes a metric. Metric values are scalars of floating-point type.

1.1.2 Constraints

1.1.3 id property
A metric SHALL contain a property named id whose value is string containing a stable, opaque identifier for the metric.

EXAMPLE: “vG”

1.1.4 name
A metric object MAY contain a property named name.

EXAMPLE: “Cyclomatic Complexity”.

1.1.5 granularities
A metric object MAY contain an array of strings that specify the logicalLocation.kind items that the metric applies to.

EXAMPLE: { “function” }

_I’m not sure if this isn’t overkill, but it could be of use in cases where the tool does not compute the value of a particular metric, in which case the defaultValue property would apply._

1.1.6 shortDescription
A metric object MAY contain a property named shortDescription
EXAMPLE: “A measure of the control flow complexity of a function”.

1.1.7 fullDescription
A metric object MAY contain a property named fullDescription
EXAMPLE: “The cyclomatic complexity of a graph with N nodes and E edges is E-N+2. It is computed on the control-flow graph of a function.”

1.1.8 defaultValue
A metric object MAY contain a property named defaultValue of floating-point type.
See granularities above for why this might be useful.

1.1.9 helpUri
A metric object MAY contain a property named helpUri.

1.1.10 formattedValue
A metric object MAY contain a property named formattedValue. This should say how the metric value is rendered.

EXAMPLE: “%5.2f”

_I don’t have a strong opinion about what format string convention should be used here. I’ve used printf only because it’s the only one I can remember. It should allow floating point values to be rendered as integers without a decimal point, and also maybe in engineering notation._

1.2 logicalLocation object
_Add the following to the specification for this object._

1.2.1 metrics property
A logicalLocation object MAY contain a property named metrics whose value is a dictionary in which the key is a string as specified in metric.id and the value is a floating-point typed value.

EXAMPLE: { “vG”: 4, “cDensity”: 24.623 }

1.3 run object
_Add the following to the specification._

A run object MAY contain a property named metrics whose value is a dictionary in which the key is a string as specified in metric.id and the value is a floating-point typed value.

EXAMPLE: { “LOC”: 1729, “xVal”: 24.623 }

**Comment by DerSaidin** [comment]
Does this proposal allow metrics to be defined for a source file? This is useful for stuff like lines of executable code.

Does putting the metrics property inside a logicalLocation mean the value of the metric is part of the definition of the logicalLocation?
Would it make more sense to invert the relationship so a metric has a location it applies to?

E.g.

```
"metrics": [
  "vG": { logicalLocationObject: 12.34, logicalLocationObject2: 34.56},
  "cDensity": { logicalLocationObject: 24.623 }
]
```

If the metric is in the logicalLocation, which logicalLocation object should it appears in? If there are 5 bugs in one function, each of those has a logicalLocation for the function, should the metrics data be copied into all of them?

**Comment by fishoak** [comment]
> Does this proposal allow metrics to be defined for a source file? This is useful for stuff like lines of executable code.

Not as written, but only because I didn't realize that files themselves are not represented as logical locations. (Someone pointed this out to me at the dinner after the meeting.) Instead, I think we should add an optional metrics property to the file object.

> Does putting the metrics property inside a logicalLocation mean the value of the metric is part of the definition of the logicalLocation?
Yes

> Would it make more sense to invert the relationship so a metric has a location it applies to?
Maybe. This would at least keep all the metrics in one place, which might be an advantage. You'll need at least three ways to identify the object that has the metric: logicalLocationKey, file (as URI presumably), and the entire run.

> If the metric is in the logicalLocation, which logicalLocation object should it appears in? If there are 5 bugs in one function, each of those has a logicalLocation for the function, should the metrics data be copied into all of them?

The result objects are with respect to a _location_ object, which may be a key into the set of logical locations. The logicalLocations property of a run object is where the metric would be placed. Thus metrics would not show up as part of result object.

**Comment by michaelcfanning** [comment]
Closing this issue for now. It is marked 'future' as a productive design area for the next version of SARIF.
