### ISSUE TITLE
install Sarif.Sdk package problem

### ISSUE THREAD

**Issue by Nachen222** [oasis-tcs/sarif-spec#443]
Severity	Code Description	Project	File	Line	Suppression State
Error	 Could not install package 'Sarif.Sdk 2.1.17'. You are trying to install this package into a project that targets 'native,Version=v0.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by lgolding** [comment]
Hi @Nachen222, sorry for not seeing this earlier. I'm going to close this issue because it relates to the SARIF SDK rather than to the SARIF specification. If you are still having a problem, please file an issue in https://github.com/microsoft/sarif-sdk.

The current version of the SDK is 2.1.25. Please let us know if you still have this problem. We have installed the SDK in many projects without seeing this issue, so it is possible the problem lies in the target project's project file rather than in the SDK package itself.

@michaelcfanning FYI
