### ISSUE TITLE
Duplication of v2.1.0 JSON schema

### ISSUE THREAD

**Issue by lcartey** [oasis-tcs/sarif-spec#448]
The v2.1.0 schema is duplicated in two places in the repository:

https://github.com/oasis-tcs/sarif-spec/blob/master/Schemata/sarif-schema-2.1.0.json
https://github.com/oasis-tcs/sarif-spec/blob/master/Documents/CommitteeSpecifications/2.1.0/sarif-schema-2.1.0.json

Furthermore, they are not byte-for-byte identical - the former uses CRLF line endings, whereas the latter uses LF line endings.

Do we need two copies? If so, can we make them identical?

**Comment by lgolding** [comment]
@lcartey @michaelcfanning 

There are multiple copies because we drop a copy into the folder for each publicly reviewed version. That copy is the version as it existed at the time we opened the ballot. There will be still yet another copy for the final version we send out in the "call for consent".

The LF version is correct (and it took a little git config juggling for me to get it there in that form). When all is done, I'll copy the final balloted version over the one in the Schemata folder. I'll leave this issue open in the meantime.

**Comment by michaelcfanning** [comment]
@lgoding, I believe we are finished here? if so, can we close this?

**Comment by lgolding** [comment]
Yes, all the right things are in all the right places.
