### ISSUE TITLE
Consider: adding field for cryptographically secure digital signature

### ISSUE THREAD

**Issue by fishoak** [oasis-tcs/sarif-spec#47]
The discussion on "provenance" at the last meeting got me thinking about whether SARIF ought to allow for cryptographic digital signatures associated with analysis runs. This would yield confidence to the user that the results had not been tampered with.

We had a situation a few years ago where a user of CodeSonar wished to produce reports that were to go to a certifying authority in support of a safety assurance argument. They were worried that the HTML output was too easy to edit, and they did not trust their developers not to do so. 

(In the end they settled for unsigned PDF because they thought it was sufficiently more difficult to edit that it was enough of a barrier to discourage tampering! Go figure.)

**Comment by michaelcfanning** [comment]
This is a good suggestion. There are existing patterns, obviously, for signing text, XML, etc., that we should consider.

**Comment by sdrees** [comment]
Adhoc feedback: 👍 ... as long as we do not name the root property / key `pandorasBox` and more seriously iff (IMO) we can provide the rules for the operations of combining, splitting, comparing and their relation to the incoming and outgoing "trust" levels this could be an interesting task for a format. Otherwise this could become a problem like e.g. inline markup can easily become one for multi-document operations on the presentation layer.

**Comment by michaelcfanning** [comment]
It looks like the 'JSON Object Signing and Encryption' standard was designed for this. The mechanism takes a payload of the base64 encoded JSON file, which it then packaged in a JSON object which adds everything required for verifying/decrypting, etc.

Below is one of the relevant RFCs and a web page that provides some illustrative examples. 

This standard doesn't require that any JSON file have anything added to it. And so it appears that there is no work to do here in the SARIF format.

https://tools.ietf.org/html/rfc7515
https://ordina-jworks.github.io/security/2016/03/12/Digitally-signing-your-JSON-documents.html
