### ISSUE TITLE
Need a compliance test suite

### ISSUE THREAD

**Issue by lgolding** [oasis-tcs/sarif-spec#5]
Copied from https://github.com/sarif-standard/sarif-spec/issues/5, created by @lgolding:

Jeffrey van Gogh suggested:

When the doc is more stable, it would be great to have a compliance test suite so both producers and consumers can be sure that they're generating the right format.

**Comment by lgolding** [comment]
Comment from @michaelcfanning:

great suggestion for the sarif sdk

**Comment by lgolding** [comment]
Comment from @lgolding:

We have a set of real-world data files, and a tool to ensure they work against the current spec.

We don't have:
- [ ] A full set of hand-authored test files that exhaustively exercise the spec.
- [ ] Documentation on how to use it.

**Comment by michaelcfanning** [comment]
this looks like an issue that should be tracked elsewhere, as closing on and shipping the spec doesn't depend on it. I've marked this issue as 'resolved-deferred'. after closing on the format, we can reopen the issue here if we'd like to use this repo to drive creation of a compliance suite (otherwise, we can move the issue elsewhere).
