### ISSUE TITLE
Consider restructuring SARIF to be location, not results-focused

### ISSUE THREAD

**Issue by michaelcfanning** [oasis-tcs/sarif-spec#55]
Today, SARIF is primarily designed to render flat lists of results. The format has the beginnings of some relational structure/linkage (for example, the 'rules' and 'files' objects). If we continue down this path, you could imagine a 'locations' object to hold all referenced code locations. These locations could themselves be annotated with additional information, such as static analysis results, but also code metrics. Annotations (such as static analysis results) could themselves refer to other locations in the set, for example, by constructing a code flow associated with a result that chains a set of code locations together. 

This design change is a significant departure from the current spec and would require all existing SARIF SDK/other support to be reimplemented. A more relational design (rather than being oriented towards a flat list) would make log files much less readable. SARIF already suffers from this problem to some degree (messages can refer to a formatting string, for example, that isn't inlined with the message). At a high-level, this proposal moves the SARIF standard more towards being a rich mechanism to annotate code locations and describe relationships between them, as opposed to more strictly serving the static analysis reporting scenario.

**Comment by DerSaidin** [comment]
> Today, SARIF is primary designed to render flat lists of results. The format has the beginnings of some relational structure/linkage (for example, the 'rules' and 'files' objects). If we continue down this path, you could imagine a 'locations' object to hold all referenced code locations.

> A more relational design (rather than being oriented towards a flat list) would make log files much less readable.

Would this mean (for example) that the files object would be moved outside the run object, so several runs could refer into the the same set of files?

Could you give a more concrete example for this possible change?

**Comment by DerSaidin** [comment]
This is my impression of what you mean by "A more relational design" (using some bits of example data from the current document)...
```
{
  // I'm going to use C++ style comments
  "files": {       // map of ID to file object
    1: {
          "path": "file:///home/buildAgent/src/collections/list.cpp",
          "mimeType": "text/x-c",
          "length": 980,
          "hashes": [
            {
              "algorithm": "sha256",
              "value": "b13ce2678a8807ba0765ab94a0ecd394f869bc81"
            }
          ]
        },
    2: {
           "path": "file:///home/buildAgent/bin/app.zip",
           "mimeType": "application/zip"
        },
    3: {
           "path": "file:///home/buildAgent/bin/app.zip#/docs/intro.docx",
           "uri": "/docs/intro.docx",
           "mimeType": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
           "parentKey": 2,      // ID of file object
           "offset": 17522,
           "length": 4050
        },
  },
  "results": {      // map of ID to result object
    1: {
        //.....
        "locations": [
          {
             "file": 1,         // ID of file object
             "region": {
                 "startLine": 15,
              },
          },
        ]
    },
    2: {
        //.....
        "locations": [
          {
             "file": 1,         // ID of file object
             "region": {
                 "startLine": 123,
              },
          },
        ]
    },
    3: {
        //.....
        "locations": [
          {
             "file": 3,         // ID of file object
          },
        ]
    },
  },
  "runs": [      // list of run objects
    {
      "automationId": "A",
      //.....
      "results": [1, 2],    // list of IDs of result objects
    },
    {
      "automationId": "B",
      //.....
      "results": [1, 3]     // list of IDs of result objects  (note shared data)
    }
  ]
}
```

In my experience, the trade offs for this option are:

Negatives:
- More complex to read or write.

Positives:
- Much smaller reports (with or without compression).
- Easier to compare (difference) reports.
  - Looking at run objects you can compare [1,2] to [1,3] and only look at the IDs.
    - No need to do a deep comparison.

I would favor a more relational design like this.

**Comment by DerSaidin** [comment]
After hearing the discussion in the meeting, I think there may be two separate ideas here.

1) changing the object model [1] SARIF to be attaching information to locations
  (e.g. providing additional information about the code and its structure)
2) changing the structure of the encoding to be referential instead of flat
  (keeping the same object model of SARIF, but with references instead of duplicates)

My comments had 2) in mind. I'm unclear if this issue is looking at 1) or 2), or both together?


[1] I'm unsure if "object model" is the correct term.
Looking at [these definitions](https://en.wikipedia.org/wiki/Logical_data_model), it may be clearer to say idea 1) is about changing the logical data model, and idea 2) is about changing the physical data model (specifically how normalized it is - a flat file format being completely denormalized).

**Comment by lgolding** [comment]
@michaelcfanning @DerSaidin Let's discuss this at the F2F meeting. I'll just contribute a couple of thoughts here.

For all of these points I'm about to make, I want to clarify that I'm only describing _why things are as they are today_. I'm not at all saying that things have to stay the way they are.

1. The original rationale for allowing a `sarifLog` to contain multiple `run` objects was to allow you to ship a collection of runs over the wire in a single batch. Say, your team runs 10 different analysis tools on each nightly build, and you want to store them all together. We didn't anticipate any connections among runs, and that's why the `sarifLog` object contains literally nothing except a SARIF version number property and an array of `run` objects.

2. The spirit of the design from the beginning was to have there be a close relationship between the "logical data model" on the one hand, and the serialization on the other. In fact, the build process for the SARIF SDK generates the object model (classes like `Run` and `PhysicalLocation`) directly from the JSON schema that describes the serialization format.

3. The object model is such that a static analysis tool can emit each result to the output file as it finds it; the tool does not have to buffer up all the results and emit them at the end. The design proposed above would require tools to buffer all their results. In fact, it would require some software component -- it's not clear to me what that component would be -- to buffer results across runs of _multiple tools_, and only emit them once all the tools have finished their analysis. I'm not sure how practical this would be.

Again, this is a great topic for us to discuss at the F2F meeting. -- Larry

**Comment by michaelcfanning** [comment]
We decided to close this issue as too intrusive a change at this point in the F2F meeeting
