### ISSUE TITLE
Consider adding `reportingDescriptor.uiLabel` property

### ISSUE THREAD

**Issue by michaelcfanning** [oasis-tcs/sarif-spec#567]
Rules contain an 'id' (an opaque, stable id) and a 'name' (a human-readable, non-stable identifier that is often compact, i.e. rendered with no spaces, etc.

We've received feedback that something like a `uiLabel` would also be valuable. This is a human-readable title/name of the rule, rendered as a user-facing string/sentence.

There could be a better, clearer name than `uiLabel`.

**Comment by adityasharad** [comment]
I suggest we use `shortDescription.text` for this purpose rather than adding another field. Today this is what GitHub code scanning will render as the human-visible label for the rule that produced an alert: https://docs.github.com/en/code-security/code-scanning/integrating-with-code-scanning/sarif-support-for-code-scanning#reportingdescriptor-object

**Comment by dmk42** [comment]
Discussed again in SARIF TC on 14 Nov 2024.
We decided to adopt @adityasharad 's solution from above. This means we would not need a `uiLabel` property, so the TC decided to close this issue.
