### ISSUE TITLE
Consider URL protocol to reference internal files and provide an associated region

### ISSUE THREAD

**Issue by michaelcfanning** [oasis-tcs/sarif-spec#57]
We may support markdown in results messages. If so, it would be useful if markdown's embedded links could refer to a file referenced within the log file itself (that file could be embedded in the log file). 

E.g.,
sarif-log://somefilename.cpp/?startLine=1,startColum=7

**Comment by lukecartey** [comment]
We could consider using the fragment identifier of the URI for the line and column information, rather than the query string, as the fragment identifier is intended to refer to a secondary resource within the primary resource. For example, `sarif-log://somefilename.cpp#startLine=1,startColumn=7`.

[RFC 5147](https://tools.ietf.org/html/rfc5147) is an example of a relevant RFC which specifies such fragment identifiers for locations and regions in text/plain MIME entities. That RFC only allows you to specify regions by lines or chars, not both - we may prefer to allow a similar range of options to the existing SARIF "region" object.

**Comment by DerSaidin** [comment]
Would these URI have more of a path than just the filename?

For example, repository, revision, path within repository:
`sarif-log://repositoryfoo/eb3450321eda/src/baz/somefilename.cpp#startLine=1,startColumn=7`

**Comment by michaelcfanning** [comment]
The idea here is that the protocol specifically points to a file that is itself part of the SARIF 'files' object. See 5.12.9. The URL referenced here (which is part of the file object) could, in fact, refer to a repository link. 

https://rawgit.com/sarif-standard/sarif-spec/master/Static%20Analysis%20Results%20Interchange%20Format%20(SARIF).html#run-files

**Comment by michaelcfanning** [comment]
Luke, in re: RFC 5147, this is an interesting format. One concept that hadn't occurred to me was the 'integrity' check, that's interesting. I agree that using a fragment would make sense. One issue is that we already reserve the fragment portion of the URL to help express nested items in file objects. I note, however, that the spec requires any fragment that refers to a nested file to be absolute (prefixed with a leading slash). We could reserve fragments without a leading slash to specify code regions.

I think I'd propose that we allow for all possible region properties in the fragment, along with a 'message' (which would be a plain-text value that could be displayed on hovering over a selected region). The population of the fragment would follow the same requirements as populating any region object (in terms of required properties, etc.)

https://somefile.cpp#startLine=7,endLine=8,message="This is the hover message for the selected region"

Obviously, everything s/be properly encoded.

**Comment by DerSaidin** [comment]
```
"files": {
    "file:///C:/Code/main.c": {
        "mimeType": "text/x-c",
        "hashes": [
            {
                "value": "b13ce2678a8807ba0765ab94a0ecd394f869bc81",
                "algorithm": "sha256"
            }
        ]
    }
}
```

So how would a URI refer to this file object?

The key for this object is the string `"file:///C:/Code/main.c"`.
I don't think we want to encode that string directly in the URI, e.g.
`sarif-log://file%3A%2F%2F%2FC%3A%2FCode%2Fmain.c#startLine=1,startColumn=7`

If we're not accessing the file object by the string key, does it have special handling for the path in that string key, to bring it into the URL structure? e.g.
`sarif-log://file/C:/Code/main.c#startLine=1,startColumn=7`
This would involve generating the matching string from the path of the URI to use as a key, right?

Since the file key is itself a URI should it just use that?
`file:///C:/Code/main.c#startLine=1,startColumn=7`
The URI before the hash MUST be a key in the files list, within the same run object the URI appears.

**Comment by michaelcfanning** [comment]
Larry pointed out offline that we don't require a special protocol for referencing the internal 'files' member. Consumers can simply try to use a URI as a look-up key into the files member if it exists (to see whether that file has been embedded in the log).

Larry's right. This issue should therefore only be used to track whether we want to specify a region + message in a fragment associated with a URI.

Note that if we take this change, we could consider dropping region from the physicalLocation object (since the region could be expressed as a fragment on its uri member).

**Comment by lgolding** [comment]
As discussed in TC Meeting #&#xfeff;7 (Nov. 29, 2017), we agree that this is not necessary. This is because internal file references will be of the form `[<link text>][<link target>]`, where `<link target>` will simply be a non-negative integer that matches the (new) `id` property on one of the `physicalLocation` objects in the result.

If in future we need another way to refer to a location, we can introduce a scheme like `location:` at that time.
