### ISSUE TITLE
Consider a tool validation or 'selectivity' annotation

### ISSUE THREAD

**Issue by michaelcfanning** [oasis-tcs/sarif-spec#59]
'Validation' in this case refers to the degree to which a result is determined to be a true positive or not. The PolySpace Verifier, for example, annotates results with designations such as 'safe', 'violation', 'dead' (for dead code) or 'open' (not conclusively determined) to bucket results returned by its abstract interpretation engine. This provides for 'selectivity' in results, meaning that the ability of consumers to select the best or most appropriate results is maximized. Note that these PolySpace annotations are not mutually exclusive (e.g., a determination could refer to a pattern that's demonstrably safe but also which occurs in dead code). This example also demonstrates some fuzziness in the taxonomy if viewed strictly as a 'validation' annotation, as the condition of being dead code is a specific attribute of a code location/assumed execution state and not strictly a statement around validation. 

There is an additional human component for validation that inevitably needs to be applied to static analysis results. These elements are captured in #48 and not covered here. This issue relates specifically to the question of whether we should provide a placeholder for tool-provided annotations that relate.

What tools emit similar data? What observations do tools return about code locations or presumed violations that would be useful to include in a set of annotations/attributes? Is a property of this kind too tightly coupled with a narrow subset of analysis engines? Could it be covered with tags/other decoration schemes?

**Comment by sipma** [comment]
The Kestrel Technology KT Advance C Analyzer emits the same designations as PolySpace, primarily  safe, violation, open, and optionally dead code as an extra annotation (since dead code is strictly speaking vacuously safe, but not in a useful way). 

In the context of our analyzer, the designation safe means that we have a proof that no violation of a given property can occur at a given statement assuming the execution up to that statement is valid (inductive hypothesis). The designation violation generally means that a given property is violated at a given statement for all executions. This, of course, is not very common, but is a consequence of using over-approximating abstract interpretation as an analysis engine. So in practice, some "bugs" will be reported as violations, but the majority of "bugs" will be reported as open, since the violation will generally occur in only a small subset of the executions.

The most important feature of a sound analyzer is that it is exhaustive, that is, a proof obligation is generated for every statement/instruction that could possibly violate a given property. For example, the KT Advance C Memory Safety Analyzer generates about 2-5 proof obligations per line of code, which all need to be proven safe to prove absence of memory safety vulnerabilities. Every proof obligation that cannot be proven either safe or a violation must be investigated: it either indicates the possibility of a violation, or a missing assumption that must be made explicit (e.g. a string can be assumed to be less than a few GB long), or simply a failure of the analyzer to find a proof, because stronger invariants are required.

**Comment by michaelcfanning** [comment]
We are tracking all open issues of this kind in #215
