### ISSUE TITLE
Document recommendations for serialization order

### ISSUE THREAD

**Issue by lgolding** [oasis-tcs/sarif-spec#70]
Document a recommended order in which a SARIF producer should emit the log file to enable it to be consumed in a streaming manner. For example, the spec already says that the `log.version` property should come first, to enable the rest of the file to be parsed.

This work item falls into two parts:

1. Capturing the ordering recommendations somewhere.
2. Deciding what's the best place to put them. Inline in various sections of the spec? As a non-normative Appendix to the spec? As a separate Committee Note, so as not to hold up publication of the spec?

**Comment by michaelcfanning** [comment]
This is a good topic. Note that deterministic ordering is also useful to textual diffs of files run-over-run. Ordering of elements also has implications for producers. To emit the 'files' property, for example, a producer needs to have a complete understanding of all results that will be emitted (in order to produce the comprehensive set of files to which they prefer. This means that a producer who would like to minimize state retained during logging might not want to emit this information. 

It's useful in many contexts to post-process SARIF files in order to do things like 1) construct a comprehensive 'files' element for tools that don't do so, 2) embed reference files in the SARIF log as part of producing a comprehensive/diagnosable log file for a work item, 3) etc.. This would typically be done by a SARIF processor that itself has access to various scan targets/artifacts and augments/makes consistent SARIF delivered by multiple tools. Might be worth noting this as a practical mechanism for handling situations where there is some particular pressure for time/memory efficiency to produce a preliminary SARIF log.

**Comment by michaelcfanning** [comment]
This topic is being covered in #210, in terms of high-level properties ordering. We should also explicitly discuss the ordering of arrays, etc., for diffing as part of this discussion. This topic is approved, but marked as requiring technical discussion for CSD.2.

**Comment by michaelcfanning** [comment]
#210 is now approved. Closing this item as duplicate (as we will address ordering in the other item).

**Comment by lgolding** [comment]
@michaelcfanning Agreed.
