### ISSUE TITLE
Support edge properties for codeFlow paths

### ISSUE THREAD

**Issue by lukecartey** [oasis-tcs/sarif-spec#71]
The `codeFlow` element can be considered as representing a path through an arbitrary graph over code elements. However, there are limits to the type of paths that can currently be represented with `codeFlow`s because properties can only occur on the node, not the edge.

For example, a call graph may have nodes which represent functions, and edges which represent calls and call returns. A `codeFlow` through this graph would not currently be able to distinguish between the `call` and `callReturn` edges without introducing extra nodes into the graph for the call itself.

**Comment by michaelcfanning** [comment]
I see what you're pointing at. Why couldn't the originating function (which contains the call site) be used as the decorated node for this case? Since we're dealing with a path through a graph, every edge has an associated node (the one to which we're traversing). Current design states that this 'target' node can be decorated with a property that qualifies the edge to it. Help me understand more clearly why this breaks down if the call graph doesn't introduce locations for actual call sites.

What are your thoughts on how to fix this problem? Would we introduce an edge construct? So that A calls B would be rendered as a sequence of 1) node representing A, 2) edge representing a call, 3) node representing the callee B?

**Comment by lgolding** [comment]
@michaelcfanning @lukecartey The existing `codeFlow` element already represents calls and returns. A SARIF `codeFlow` object is a sequence of `annotatedCodeLocation` objects, each of which in turn consists of a `physicalLocation` together with metadata that describes that location.

So for example, suppose we have this code:
```
// File foo.c:
1. void f()
2. {
3.    int n = g();
4. }

// File bar.c:
1. void g()
2. {
3.    printf("Hello");
4.    return 42;
5. }
```
Then the `codeFlow` object might look like this:
```
{
  "locations": [
    {
      "physicalLocation": {
        "uri": "foo.c",
        "region": {
          "startLine": 3
        }
      },
      "kind": "call"
    },
    {
        "physicalLocation": {
          "uri": "bar.c",
          "region": {
            "startLine": 3
          }
        },
        "kind": "functionEnter"
    },
    {
        "physicalLocation": {
          "uri": "bar.c",
          "region": {
            "startLine": 4
          }
        },
        "kind": "functionReturn"
    },
    {
        "physicalLocation": {
          "uri": "bar.c",
          "region": {
            "startLine": 5
          }
        },
        "kind": "functionExit"
    },
    {
      "physicalLocation": {
        "uri": "foo.c",
        "region": {
          "startLine": 3
        }
      },
      "kind": "callReturn"
    },
  ]
}
```
(The difference between `functionReturn` and `functionExit` is subtle; see the spec.)

The point here is that a SARIF code flow is no really "a path through a graph"; rather, it is a "sequence of locations".

Are you suggesting that we choose a different representation -- one that really is "a path through a graph" -- because there is additional information that you would like to associate with the edges of that graph?

**Comment by michaelcfanning** [comment]
I believe Luke agrees with your position. We have agreed to close this issue for now.

**Comment by lukecartey** [comment]
Apologies, I made a poor job of explaining this issue.

The problem I was intending to highlight here is that the `kind` associated with each `annotatedCodeLocation` conflates edge and node kinds. For certain types of path, this may mean we need to introduce additional nodes into our path in order to use the kinds as designed.

For example, the `call` kind is both referring to the kind of the node itself, but also the kind of the outgoing edge. In contrast, the `callReturn` is not a node type, but is referring to the type of the incoming edge.

Here's the concrete example I was thinking of:
```
// File foo.c:
1. void f()
2. {
3.    g();
4.    h();
5. }

// File bar.c:
1. int g()
2. {
3.    printf("Hello");
4. }
5. int h()
6. {
7.    printf("Hello");
8. }
```
Now, assume we have a call graph which talks only about the functions i.e. for whatever reason, we don't want to represent the call nodes explicitly. In that case, we may want to represent the following path:

`f() -> g() -> f() -> h() -> f()`

We can represent this as a codeflow without kinds like this:

```
{
  "locations": [
    {
      "step": 1,
      "physicalLocation": {
        "uri": "foo.c",
        "region": {
          "startLine": 1
        }
      },
    },
    {
      "step": 2,
      "physicalLocation": {
        "uri": "bar.c",
        "region": {
          "startLine": 1
        }
      },
    },
    {
      "step": 3,
      "physicalLocation": {
        "uri": "foo.c",
        "region": {
          "startLine": 1
        }
      },
    },
    {
      "step": 4,
      "physicalLocation": {
        "uri": "bar.c",
        "region": {
          "startLine": 5
        }
      },
    },
    {
      "step": 5,
      "physicalLocation": {
        "uri": "foo.c",
        "region": {
          "startLine": 1
        }
      },
    },
  ]
}
```
This is a reasonable codeflow, but proves to be difficult to assign a sensible set of kinds to these annotatedCodeLocation. In particular, Step 3 would ideally be both a "callReturn" and a "call", as the incoming edge is a call return, but the outgoing edge is a call.

Of course, we could solve this by introducing additional `annotatedCodeLocation`s, but that puts an extra burden on the tool producing this path, as well as bloating the representation.

---

One reason I'm interested in thinking about this is that our queries are flexible, in that they allow arbitrary paths to be associated with a result. Unlike a tool with a fixed "path model", we can't just write a single converter from "our" codeFlow model to SARIF, because it could be specific to a particular query.

As for suggestions on what to do next, perhaps we can look at having an `edgeKind` property, that more explicitly talks about the type of the edge? I think an explicit representation of the edge would probably be less fluent than the current approach.
